spring:
  profiles:
    active: db

server:
  port: 80

pagehelper:
  helper-dialect: mysql

logging:
  file: spring.log
  level:
    com:
      cskaoyan:
        mall:
          mallStart:
            mapper: debug
