spring:
  profiles:
    active: db
  resources:
    static-locations: file:D:\spring

myfile:
  config:
    localhost: http://192.168.3.97:80
    filepath: /wx/storage/fetch/

server:
  port: 80

pagehelper:
  helper-dialect: mysql

logging:
  file: spring.Log
  level:
    com:
      cskaoyan:
        mall:
          mallStart:
            mapper: debug
mybatis:
  type-handlers-package: com.cskaoyan.mall.mallStart.typehandler

