spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_405?useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 80
